apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: pipeline-service-rh1p
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pipeline-service-rh1p
    app.kubernetes.io/part-of: pipeline-service
  name: pipeline-service-rh1p
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: pipeline-service-rh1p
status:
  loadBalancer: {}
